# Generated by Django 3.2.5 on 2022-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.IntegerField(unique=True),
        ),
    ]
