# Generated by Django 3.2.5 on 2022-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=15)),
                ('data_pagamento', models.DateField()),
                ('data_pagamento_esperado', models.DateField()),
                ('tipo_despesa', models.CharField(max_length=30)),
                ('conta', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
    ]
