# Generated by Django 3.2.5 on 2022-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
